version: '3.8'

services:
  ai-chatbot-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env  # Load environment variables from .env file
    environment:
      # Override defaults if needed
      - HOST=0.0.0.0
      - PORT=8000
    volumes:
      # Mount source code for development (optional)
      - ./app:/app/app:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Add a simple frontend for testing
  # nginx:
  #   image: nginx:alpine
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #   depends_on:
  #     - ai-chatbot-api

networks:
  default:
    name: ai-chatbot-network 